# GitHub Copilot カスタムレビュールール設定
# 全てのレビューコメントを日本語で出力するためのルール

version: "1.0"

# 基本設定
settings:
  language: "ja"
  locale: "ja-JP"
  review_language: "japanese"
  
# 適用範囲
scope:
  files: ["**/*"]  # 全てのファイルに適用
  exclude: 
    - "node_modules/**"
    - "dist/**" 
    - "build/**"
    - "*.min.js"

# レビュールール
rules:
  # コードレビューの言語設定
  code_review:
    comment_language: "japanese"
    explanation_style: "detailed"
    use_japanese_technical_terms: true
    
  # 具体的なルール
  review_guidelines:
    # 1. 言語設定
    - rule: "language_consistency"
      description: "全てのレビューコメントを日本語で記述する"
      action: "enforce_japanese"
      examples:
        - bad: "Consider using const instead of let for better performance"
        - good: "パフォーマンス向上のため、letの代わりにconstの使用を検討してください"
    
    # 2. 技術用語の説明
    - rule: "technical_terms_explanation"
      description: "技術用語には日本語での説明を含める"
      action: "add_japanese_explanation"
      examples:
        - bad: "Use async/await"
        - good: "async/await（非同期処理）を使用してください"
    
    # 3. 改善提案の詳細説明
    - rule: "detailed_improvement_suggestions"
      description: "コードの改善提案は日本語で具体的に説明する"
      action: "provide_detailed_japanese_explanation"
      examples:
        - bad: "Refactor this function"
        - good: "この関数は責務が多すぎるため、単一責任の原則に従って複数の関数に分割することを推奨します"

# コメントテンプレート
comment_templates:
  # コード品質に関するコメント
  code_quality:
    - template: "コードの可読性を向上させるため、{suggestion}を検討してください。"
    - template: "パフォーマンス向上のため、{optimization}の実装をお勧めします。"
    - template: "セキュリティの観点から、{security_concern}について確認をお願いします。"
  
  # ベストプラクティスに関するコメント  
  best_practices:
    - template: "一般的なベストプラクティスとして、{practice}の採用をお勧めします。"
    - template: "保守性を向上させるため、{maintainability_suggestion}を検討してください。"
    
  # バグ・問題指摘
  bug_detection:
    - template: "潜在的な問題として、{issue}が発生する可能性があります。{solution}の実装をお勧めします。"
    - template: "エラーハンドリングが不十分です。{error_handling}を追加してください。"

# 特定ファイルタイプ別の設定
file_type_rules:
  # JavaScript/TypeScriptファイル
  "*.{js,ts,jsx,tsx}":
    focus_areas:
      - "型安全性の確保"
      - "非同期処理の適切な実装"
      - "エラーハンドリングの充実"
    
  # CSSファイル
  "*.{css,scss,sass}":
    focus_areas:
      - "レスポンシブデザインの考慮"
      - "保守性の高いスタイル記述"
      - "パフォーマンスへの配慮"
  
  # HTMLファイル
  "*.html":
    focus_areas:
      - "アクセシビリティの確保"
      - "セマンティックなマークアップ"
      - "SEOの最適化"

# レビューの優先度
priority_levels:
  critical: "重要：即座に修正が必要な問題"
  high: "高：リリース前に修正を推奨"
  medium: "中：時間があるときに改善を検討"
  low: "低：将来的な改善点として記録"

# 日本語表現のガイドライン
japanese_style_guide:
  tone: "丁寧語を使用"
  formality: "ビジネス適切なレベル"
  technical_terms: "必要に応じて英語併記"
  suggestions: "建設的で具体的な提案"