import { describe, it, expect, vi, beforeEach } from 'vitest';
import {
  isAutoGeneratedGroup,
  findGroupByDomain,
  createGroupForDomain,
  addTabToGroup
} from '../../src/utils/group';
import { AUTO_GROUP_PREFIX, DEFAULT_GROUP_COLORS } from '../../src/constants';

describe('Group Utils', () => {
  beforeEach(() => {
    vi.clearAllMocks();
  });

  describe('isAutoGeneratedGroup', () => {
    it('should return true for auto-generated group', async () => {
      const mockGroup = {
        id: 1,
        title: `${AUTO_GROUP_PREFIX} example.com`,
        color: 'blue' as chrome.tabGroups.ColorEnum,
        collapsed: false,
        windowId: 1
      };

      vi.mocked(chrome.tabGroups.query).mockResolvedValue([mockGroup] as chrome.tabGroups.TabGroup[]);

      const result = await isAutoGeneratedGroup(1);
      expect(result).toBe(true);
    });

    it('should return false for manually created group', async () => {
      const mockGroup = {
        id: 1,
        title: 'My Custom Group',
        color: 'blue' as chrome.tabGroups.ColorEnum,
        collapsed: false,
        windowId: 1
      };

      vi.mocked(chrome.tabGroups.query).mockResolvedValue([mockGroup] as chrome.tabGroups.TabGroup[]);

      const result = await isAutoGeneratedGroup(1);
      expect(result).toBe(false);
    });

    it('should return false for group with no title', async () => {
      const mockGroup = {
        id: 1,
        color: 'blue' as chrome.tabGroups.ColorEnum,
        collapsed: false,
        windowId: 1
      };

      vi.mocked(chrome.tabGroups.query).mockResolvedValue([mockGroup] as chrome.tabGroups.TabGroup[]);

      const result = await isAutoGeneratedGroup(1);
      expect(result).toBe(false);
    });

    it('should return false when group not found', async () => {
      vi.mocked(chrome.tabGroups.query).mockResolvedValue([]);

      const result = await isAutoGeneratedGroup(1);
      expect(result).toBe(false);
    });

    it('should handle chrome API errors', async () => {
      vi.mocked(chrome.tabGroups.query).mockRejectedValue(new Error('API Error'));

      const result = await isAutoGeneratedGroup(1);
      expect(result).toBe(false);
    });
  });

  describe('findGroupByDomain', () => {
    it('should find existing auto-generated group for domain', async () => {
      const mockGroups = [
        {
          id: 1,
          title: `${AUTO_GROUP_PREFIX} example.com`,
          color: 'blue' as chrome.tabGroups.ColorEnum,
          collapsed: false,
          windowId: 1
        },
        {
          id: 2,
          title: 'Manual Group',
          color: 'red' as chrome.tabGroups.ColorEnum,
          collapsed: false,
          windowId: 1
        }
      ];

      vi.mocked(chrome.tabGroups.query).mockResolvedValue(mockGroups as chrome.tabGroups.TabGroup[]);

      const result = await findGroupByDomain('example.com');
      expect(result).toEqual({
        id: 1,
        title: `${AUTO_GROUP_PREFIX} example.com`,
        color: 'blue',
        collapsed: false,
        windowId: 1,
        domain: 'example.com'
      });
    });

    it('should return null when no auto-generated group exists for domain', async () => {
      const mockGroups = [
        {
          id: 1,
          title: `${AUTO_GROUP_PREFIX} other.com`,
          color: 'blue' as chrome.tabGroups.ColorEnum,
          collapsed: false,
          windowId: 1
        }
      ];

      vi.mocked(chrome.tabGroups.query).mockResolvedValue(mockGroups as chrome.tabGroups.TabGroup[]);

      const result = await findGroupByDomain('example.com');
      expect(result).toBeNull();
    });

    it('should filter by windowId when provided', async () => {
      const mockGroupsWindow1 = [
        {
          id: 1,
          title: `${AUTO_GROUP_PREFIX} example.com`,
          color: 'blue' as chrome.tabGroups.ColorEnum,
          collapsed: false,
          windowId: 1
        }
      ];

      vi.mocked(chrome.tabGroups.query).mockResolvedValue(mockGroupsWindow1 as chrome.tabGroups.TabGroup[]);

      const result = await findGroupByDomain('example.com', 1);
      expect(result?.id).toBe(1);
      expect(chrome.tabGroups.query).toHaveBeenCalledWith({ windowId: 1 });
    });

    it('should handle chrome API errors', async () => {
      vi.mocked(chrome.tabGroups.query).mockRejectedValue(new Error('API Error'));

      const result = await findGroupByDomain('example.com');
      expect(result).toBeNull();
    });
  });

  describe('createGroupForDomain', () => {
    it('should create new group for domain', async () => {
      const mockGroup = {
        id: 1,
        color: 'blue' as chrome.tabGroups.ColorEnum,
        collapsed: false,
        windowId: 1
      };

      const mockUpdatedGroup = {
        ...mockGroup,
        title: `${AUTO_GROUP_PREFIX} example.com`
      };

      vi.mocked(chrome.tabGroups.create).mockResolvedValue(mockGroup as chrome.tabGroups.TabGroup);
      vi.mocked(chrome.tabGroups.update).mockResolvedValue(mockUpdatedGroup as chrome.tabGroups.TabGroup);

      const result = await createGroupForDomain('example.com', 1);
      
      expect(result).toEqual({
        id: 1,
        title: `${AUTO_GROUP_PREFIX} example.com`,
        color: 'blue',
        collapsed: false,
        windowId: 1,
        domain: 'example.com'
      });

      expect(chrome.tabGroups.create).toHaveBeenCalledWith({
        windowId: 1
      });
    });

    it('should update group title and color after creation', async () => {
      const mockGroup = {
        id: 1,
        color: 'blue' as chrome.tabGroups.ColorEnum,
        collapsed: false,
        windowId: 1
      };

      const mockUpdatedGroup = {
        ...mockGroup,
        title: `${AUTO_GROUP_PREFIX} example.com`
      };

      vi.mocked(chrome.tabGroups.create).mockResolvedValue(mockGroup as chrome.tabGroups.TabGroup);
      vi.mocked(chrome.tabGroups.update).mockResolvedValue(mockUpdatedGroup as chrome.tabGroups.TabGroup);

      await createGroupForDomain('example.com', 1);

      expect(chrome.tabGroups.update).toHaveBeenCalledWith(1, {
        title: `${AUTO_GROUP_PREFIX} example.com`,
        color: expect.any(String)
      });
    });

    it('should handle chrome API errors', async () => {
      vi.mocked(chrome.tabGroups.create).mockRejectedValue(new Error('API Error'));

      const result = await createGroupForDomain('example.com', 1);
      expect(result).toBeNull();
    });
  });

  describe('addTabToGroup', () => {
    it('should add tab to existing group', async () => {
      vi.mocked(chrome.tabs.group).mockResolvedValue();

      const success = await addTabToGroup(123, 1);
      
      expect(success).toBe(true);
      expect(chrome.tabs.group).toHaveBeenCalledWith({
        tabIds: [123],
        groupId: 1
      });
    });

    it('should handle chrome API errors', async () => {
      vi.mocked(chrome.tabs.group).mockRejectedValue(new Error('API Error'));

      const success = await addTabToGroup(123, 1);
      expect(success).toBe(false);
    });

    it('should handle multiple tabs', async () => {
      vi.mocked(chrome.tabs.group).mockResolvedValue();

      const success = await addTabToGroup([123, 456], 1);
      
      expect(success).toBe(true);
      expect(chrome.tabs.group).toHaveBeenCalledWith({
        tabIds: [123, 456],
        groupId: 1
      });
    });
  });
});